development:
  adapter: postgresql
  database: rails_angular_database_development
  pool: 5
  timeout: 5000
  host: localhost
  username: postgres
  password: password

test:
  adapter: postgresql
  database: rails_angular_database_test
  pool: 5
  timeout: 5000
  host: localhost
  username: postgres
  password: password

production:
  adapter: postgresql
  database: rails_angular_database_production
  pool: 5
  timeout: 5000
  host: localhost
